# Generated by Django 5.0.6 on 2024-07-16 08:29

import community.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_category_product_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('category', models.ForeignKey(default=community.models.get_default_category_id, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='community.category')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
